# Generated by Django 5.2 on 2025-04-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_merge_20250428_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='profilePhoto',
            field=models.ImageField(default='static/images/profile.png', upload_to='athletes/'),
        ),
    ]
