# Generated by Django 5.2 on 2025-04-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_merge_20250429_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='athlete',
            name='twitterX',
            field=models.URLField(blank=True),
        ),
    ]
