# Generated by Django 5.2 on 2025-04-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_athlete_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='photo',
            field=models.ImageField(default='static/images/profile.png', upload_to='media/clubs/photos/'),
        ),
    ]
