# Generated by Django 5.2 on 2025-04-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_merge_20250429_1007'),
        ('account', '0012_alter_club_photo'),
    ]

    operations = [
    ]
