# Generated by Django 5.2 on 2025-05-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_remove_athlete_achievements_achievement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='athletes/photos/'),
        ),
    ]
