# Generated by Django 5.2 on 2025-05-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_alter_achievement_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='file',
            field=models.ImageField(default=0, upload_to='athletes/photos/'),
            preserve_default=False,
        ),
    ]
