# Generated by Django 5.2 on 2025-05-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'All')], default='A', max_length=1),
        ),
    ]
