# Generated by Django 5.2 on 2025-04-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_alter_payment_amount_alter_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
