# Generated by Django 5.2 on 2025-04-24 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_sport_sport_name_athlete_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='profilePhoto',
            field=models.ImageField(blank=True, default='ccount/static/image/profile-icon.jpg', upload_to='media/athletes/photos/'),
        ),
    ]
