# Generated by Django 5.2 on 2025-04-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_athlete_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='media/athletes/photos/'),
        ),
    ]
