# Generated by Django 5.2 on 2025-04-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_athlete_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='profilePhoto',
            field=models.ImageField(default='static/image/profile-icon.jpg', upload_to='media/athletes/photos/'),
        ),
        migrations.AlterField(
            model_name='club',
            name='photo',
            field=models.ImageField(default='static/image/profile-icon.jpg', upload_to='media/clubs/photos/'),
        ),
    ]
