# Generated by Django 5.2 on 2025-04-29 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_club_is_premium'),
        ('account', '0006_alter_athlete_profilephoto_alter_club_photo'),
    ]

    operations = [
    ]
