# Generated by Django 5.2 on 2025-04-29 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_athlete_facebook_athlete_instagram_athlete_twitterx'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='twitterX',
            field=models.URLField(blank=True),
        ),
    ]
