# Generated by Django 5.2 on 2025-04-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_athlete_profilephoto'),
        ('account', '0009_club_facebook_club_instagram_club_twitterx'),
    ]

    operations = [
    ]
